name: ruff

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
  
          - name: Install uv
            uses: astral-sh/setup-uv@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version-file: "pyproject.toml"

          - name: Lint code with Ruff
            run: uvx ruff check --output-format=github

          - name: Check code formatting with Ruff
            run: uvx ruff format --diff
            continue-on-error: true
